home_page: home.md        # filepath under /source/
menu_page: menu.md        # filepath under /source/
author_img: images/avatar.png              # filepath of author image
favicon_url: favicon.ico  # filepath of favicon

zoom_image: true
codeblock:
  # Code Highlight theme
  # Available values: normal | night | night eighties | night blue | night bright | solarized | solarized dark | galactic
  highlight_theme: normal

comments:
  utterances:
    enable: true
    user: iotale # your github user name
    repo: iotale.github.io # your github repo name
    theme: github-light # github-light | github-dark | github-dark-orange | icy-dark | dark-blue | photon-dark
  disqus:
    enable: false
    shortname: # your disqus shortname
  gitalk: # 基于 Preact 开发的类 Github Issue 的评论组件
    enable: false
    githubID: # your github id，通过 https://api.github.com/users/iotale 获取
    repo: # GitHub repository e.g. kaiiiz.github.io
    ClientID: # GitHub Application Client ID
    ClientSecret: # GitHub Application Client Secret
    adminUser: # GitHub repository owner and collaborators
    labels: 'gitalk' # GitHub issue labels
    distractionFreeMode: true

google_analytics: G-PNM9Q1PJJL # UA-XXXXX-Y
